DROP TABLE IF EXISTS burgers;

CREATE TABLE burgers (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  burger_name VARCHAR(45) NOT NULL,
  devoured BOOLEAN DEFAULT 0,
  createdAt TIMESTAMP NOT NULL
);
